towards sudoers.d hardening

diff --git a/usr/libexec/msgcollector/msgcollector b/usr/libexec/msgcollector/msgcollector
--- a/usr/libexec/msgcollector/msgcollector
+++ b/usr/libexec/msgcollector/msgcollector
@@ -31,7 +31,6 @@ error_handler() {
 ##
 ## scriptname: $scriptname
 ## identifier: $identifier
-## who_ami: $who_ami
 ## my_command_line_parameters: $my_command_line_parameters
 ## write_to_file: $write_to_file
 ## parentpid: $parentpid
@@ -74,7 +73,6 @@ error_handler() {
    echo "\
 scriptname: $scriptname
 identifier: $identifier
-who_ami: $who_ami
 my_command_line_parameters: $my_command_line_parameters
 parentpid: $parentpid
 ps_p_parentpid: $ps_p_parentpid
@@ -111,10 +109,6 @@ parse_cmd_options() {
                ;;
            --identifier)
                identifier="$2"
-               shift 2
-               ;;
-           --whoami)
-               who_ami_discard="$2"
                shift 2
                ;;
            --icon)
@@ -292,18 +286,8 @@ parse_cmd_options() {
 preparation() {
    trap "error_handler" ERR
 
-   if [ "$who_ami" = "" ]; then
-      who_ami=$(whoami)
-   fi
-
-   ## msgdispatcher needs to be able to read the file. Otherwise:
-   ## cat: /run/msgcollector/systemcheck/systemcheck.messagex: Permission denied
-   ## user running msgdispatcher (user "user") would need to be member of a group
-   ## which may read access all of folder /run/msgcollector.
-   umask ug=rw,o=r
-
-   if [ ! -d "/run/msgcollector/$who_ami" ]; then
-      mkdir --parents --mode ugo+rwx "/run/msgcollector/$who_ami"
+   if [ ! -d "${msgcollector_run_dir}" ]; then
+      mkdir --parents --mode ugo+rwx "${msgcollector_run_dir}"
    fi
 }
 
@@ -423,7 +407,7 @@ collector() {
 
    ## {{ --icon
    if [ ! "$icon" = "" ]; then
-      echo "$icon" > "/run/msgcollector/$who_ami/${identifier}_icon"
+      echo "$icon" > "${msgcollector_run_dir}/${identifier}_icon"
    fi
    ## }}
 
@@ -436,7 +420,7 @@ collector() {
       parentpid="0000000000"
    fi
    ## Not at this point to avoid useless files.
-   #echo "$parentpid" > "/run/msgcollector/$who_ami/${identifier}_${progressbaridx}_parentpid"
+   #echo "$parentpid" > "${msgcollector_run_dir}/${identifier}_${progressbaridx}_parentpid"
    ## }}
 
    ## {{ --titlecli
@@ -444,55 +428,55 @@ collector() {
       ## variable $titlecli exists
       ## TODO
       true "TODO: --titlecli not yet implemented in msgdispatcher"
-      #echo "$titlecli" > "/run/msgcollector/$who_ami/${identifier}_titlecli"
+      #echo "$titlecli" > "${msgcollector_run_dir}/${identifier}_titlecli"
    fi
    ## }}
 
    ## {{ --titlex
    if [ ! -z "$titlex" ]; then
       ## variable $titlex exists
-      echo "$titlex" > "/run/msgcollector/$who_ami/${identifier}_titlex"
+      echo "$titlex" > "${msgcollector_run_dir}/${identifier}_titlex"
    fi
    ## }}
 
    ## {{ --passivepopupqueuextitle
    if [ ! -z "$passivepopupqueuextitle" ]; then
       ## variable $passivepopupqueuextitle exists
-      echo "$passivepopupqueuextitle" > "/run/msgcollector/$who_ami/${identifier}_passivepopupqueuextitle"
+      echo "$passivepopupqueuextitle" > "${msgcollector_run_dir}/${identifier}_passivepopupqueuextitle"
    fi
    ## }}
 
    ## {{ --progressbartitlex
    if [ ! -z "$progressbartitlex" ]; then
       ## variable $progressbartitlex exists
-      echo "$progressbartitlex" > "/run/msgcollector/$who_ami/${identifier}_${progressbaridx}_progressbartitlex"
+      echo "$progressbartitlex" > "${msgcollector_run_dir}/${identifier}_${progressbaridx}_progressbartitlex"
    fi
    ## }}
 
    ## {{ --typecli
    if [ "$messagecli" = "1" ]; then
-      if [ -f "/run/msgcollector/$who_ami/${identifier}_typecli" ]; then
-         old_typecli="$(cat "/run/msgcollector/$who_ami/${identifier}_typecli")"
+      if [ -f "${msgcollector_run_dir}/${identifier}_typecli" ]; then
+         old_typecli="$(cat "${msgcollector_run_dir}/${identifier}_typecli")"
       fi
 
       if [ "$old_typecli" = "info" ]; then
          if [ "$typecli" = "error" ]; then
             ## Upgrade from info to error.
-            write_typecli_to_file "error" "/run/msgcollector/$who_ami/${identifier}_typecli"
+            write_typecli_to_file "error" "${msgcollector_run_dir}/${identifier}_typecli"
          elif [ "$typecli" = "warning" ]; then
             ## Upgrade from info to warning.
-            write_typecli_to_file "warning" "/run/msgcollector/$who_ami/${identifier}_typecli"
+            write_typecli_to_file "warning" "${msgcollector_run_dir}/${identifier}_typecli"
          fi
       elif [ "$old_typecli" = "warning" ]; then
          if [ "$typecli" = "error" ]; then
             ## Upgrade from warning to error.
-            write_typecli_to_file "error" "/run/msgcollector/$who_ami/${identifier}_typecli"
+            write_typecli_to_file "error" "${msgcollector_run_dir}/${identifier}_typecli"
          fi
       elif [ "$old_typecli" = "error" ]; then
          true
       else
          if [ ! "$typecli" = "" ]; then
-            write_typecli_to_file "$typecli" "/run/msgcollector/$who_ami/${identifier}_typecli"
+            write_typecli_to_file "$typecli" "${msgcollector_run_dir}/${identifier}_typecli"
          fi
       fi
    fi
@@ -500,27 +484,27 @@ collector() {
 
    ## {{ --typex
    if [ "$messagex" = "1" ]; then
-      if [ -f "/run/msgcollector/$who_ami/${identifier}_typex" ]; then
-         old_typex="$(cat "/run/msgcollector/$who_ami/${identifier}_typex")"
+      if [ -f "${msgcollector_run_dir}/${identifier}_typex" ]; then
+         old_typex="$(cat "${msgcollector_run_dir}/${identifier}_typex")"
       fi
 
       if [ "$old_typex" = "info" ]; then
          if [ "$typex" = "error" ]; then
             ## Upgrade from info to error.
-            echo "error" > "/run/msgcollector/$who_ami/${identifier}_typex"
+            echo "error" > "${msgcollector_run_dir}/${identifier}_typex"
          elif [ "$typex" = "warning" ]; then
             ## Upgrade from info to warning.
-            echo "warning" > "/run/msgcollector/$who_ami/${identifier}_typex"
+            echo "warning" > "${msgcollector_run_dir}/${identifier}_typex"
          fi
       elif [ "$old_typex" = "warning" ]; then
          if [ "$typex" = "error" ]; then
             ## Upgrade from warning to error.
-            echo "error" > "/run/msgcollector/$who_ami/${identifier}_typex"
+            echo "error" > "${msgcollector_run_dir}/${identifier}_typex"
          fi
       elif [ "$old_typex" = "error" ]; then
          true
       else
-         echo "$typex" > "/run/msgcollector/$who_ami/${identifier}_typex"
+         echo "$typex" > "${msgcollector_run_dir}/${identifier}_typex"
       fi
    fi
    ## }}
@@ -528,14 +512,14 @@ collector() {
    ## {{ --messagex
    if [ "$messagex" = "1" ]; then
       pretty_type_x "$typex"
-      write_to_file="/run/msgcollector/$who_ami/${identifier}_messagex"
+      write_to_file="${msgcollector_run_dir}/${identifier}_messagex"
       append_to_file
    fi
    ## }}
 
    ## {{ --messagecli
    if [ "$messagecli" = "1" ]; then
-      write_to_file="/run/msgcollector/$who_ami/${identifier}_messagecli"
+      write_to_file="${msgcollector_run_dir}/${identifier}_messagecli"
       if [ ! -z "$message" ]; then
          ## variable $message exists
          message="$(/usr/libexec/msgcollector/striphtml "$message")"
@@ -549,7 +533,7 @@ collector() {
 
    ## {{ --waitmessagecli
    if [ "$waitmessagecli" = "1" ]; then
-      write_to_file="/run/msgcollector/$who_ami/${identifier}_waitmessagecli"
+      write_to_file="${msgcollector_run_dir}/${identifier}_waitmessagecli"
       if [ ! -z "$message" ]; then
          ## variable $message exists
          message="$(/usr/libexec/msgcollector/striphtml "$message")"
@@ -570,14 +554,14 @@ collector() {
       if [ "$message" = "" ]; then
          message="message was empty after striphtml."
       fi
-      write_to_file="/run/msgcollector/$who_ami/${identifier}_passivepopupqueuex"
+      write_to_file="${msgcollector_run_dir}/${identifier}_passivepopupqueuex"
       append_to_file
    fi
    ## }}
 
    ## {{ --animate
    if [ "$animate" = "1" ]; then
-      touch "/run/msgcollector/$who_ami/${identifier}_${progressbaridx}_progressbarx_animate"
+      touch "${msgcollector_run_dir}/${identifier}_${progressbaridx}_progressbarx_animate"
    fi
 
    ## {{ --progressx
@@ -592,29 +576,29 @@ collector() {
       #echo "msgcollector: progressx: $progressx | caller: $PPID | $caller" >> /home/user/progresslog
 
       if [ "$verbose" = "1" ]; then
-         bash -x /usr/libexec/msgcollector/msgprogress --identifier "$identifier" --whoami "$who_ami" --progressbaridx "${progressbaridx}" --progress "$progressx"
+         bash -x /usr/libexec/msgcollector/msgprogress --identifier "$identifier" --progressbaridx "${progressbaridx}" --progress "$progressx"
       else
          ## & disown to prevent long waiting.
-         /usr/libexec/msgcollector/msgprogress --identifier "$identifier" --whoami "$who_ami" --progressbaridx "${progressbaridx}" --progress "$progressx" & disown
+         /usr/libexec/msgcollector/msgprogress --identifier "$identifier" --progressbaridx "${progressbaridx}" --progress "$progressx" & disown
       fi
    fi
    ## }}
 
    ## {{ --forceactive
    if [ "$forceactive" = "1" ]; then
-      touch "/run/msgcollector/$who_ami/${identifier}_forceactive"
+      touch "${msgcollector_run_dir}/${identifier}_forceactive"
    fi
    ## }}
 
    ## {{ --lefttop
    if [ "$lefttop" = "1" ]; then
-      touch "/run/msgcollector/$who_ami/${identifier}_lefttop"
+      touch "${msgcollector_run_dir}/${identifier}_lefttop"
    fi
    ## }}
 
    ## {{ --parenttty
    if [ ! -z "$parenttty" ]; then
-      echo "$parenttty" > "/run/msgcollector/$who_ami/${identifier}_parenttty"
+      echo "$parenttty" > "${msgcollector_run_dir}/${identifier}_parenttty"
    fi
    ## }}
 
@@ -624,13 +608,13 @@ collector() {
          error "Variable progressbaridx is empty."
          exit 4
       fi
-      echo "$parentpid" > "/run/msgcollector/$who_ami/${identifier}_${progressbaridx}_parentpid"
+      echo "$parentpid" > "${msgcollector_run_dir}/${identifier}_${progressbaridx}_parentpid"
       message="$(/usr/libexec/msgcollector/striphtml "$message")"
-      write_to_file="/run/msgcollector/$who_ami/${identifier}_${progressbaridx}_progressbarx"
+      write_to_file="${msgcollector_run_dir}/${identifier}_${progressbaridx}_progressbarx"
       append_to_file
 
       ## Cannot run from msgdispatcher due to user mismatch permission issues.
-      /usr/libexec/msgcollector/msgprogressbar --identifier "${identifier}" --whoami "$who_ami" --progressbaridx "${progressbaridx}" --progressbartitlex "$progressbartitlex" --message "$message" $animate & disown
+      /usr/libexec/msgcollector/msgprogressbar --identifier "${identifier}" --progressbaridx "${progressbaridx}" --progressbartitlex "$progressbartitlex" --message "$message" $animate & disown
    fi
    ## }}
 }
@@ -678,28 +662,28 @@ return_status() {
 
    ## {{ --messagex
    if [ "$messagex" = "1" ]; then
-      write_to_file="/run/msgcollector/$who_ami/${identifier}_messagex"
+      write_to_file="${msgcollector_run_dir}/${identifier}_messagex"
       return_status_file
    fi
    ## }}
 
    ## {{ --messagecli
    if [ "$messagecli" = "1" ]; then
-      write_to_file="/run/msgcollector/$who_ami/${identifier}_messagecli"
+      write_to_file="${msgcollector_run_dir}/${identifier}_messagecli"
       return_status_file
    fi
    ## }}
 
    ## {{ --waitmessagecli
    if [ "$waitmessagecli" = "1" ]; then
-      write_to_file="/run/msgcollector/$who_ami/${identifier}_waitmessagecli"
+      write_to_file="${msgcollector_run_dir}/${identifier}_waitmessagecli"
       return_status_file
    fi
    ## }}
 
    ## {{ --passivepopupqueuex
    if [ "$passivepopupqueuex" = "1" ]; then
-      write_to_file="/run/msgcollector/$who_ami/${identifier}_passivepopupqueuex"
+      write_to_file="${msgcollector_run_dir}/${identifier}_passivepopupqueuex"
       return_status_file
    fi
    ## }}
@@ -710,17 +694,17 @@ return_status() {
          error "Variable progressbaridx is empty."
          exit 4
       fi
-      write_to_file="/run/msgcollector/$who_ami/${identifier}_${progressbaridx}_progressbarx"
+      write_to_file="${msgcollector_run_dir}/${identifier}_${progressbaridx}_progressbarx"
       return_status_file
    fi
    ## }}
 
    ## {{ --progressbarxrunning
    if [ "$progressbarxrunning" = "1" ]; then
-      if [ -f "/run/msgcollector/$who_ami/${identifier}_${progressbaridx}_zenityprogresspid" ]; then
+      if [ -f "${msgcollector_run_dir}/${identifier}_${progressbaridx}_zenityprogresspid" ]; then
          local pid
          ## || true to prevent race condition
-         zenity_progress_pid="$(cat "/run/msgcollector/$who_ami/${identifier}_${progressbaridx}_zenityprogresspid")" || true
+         zenity_progress_pid="$(cat "${msgcollector_run_dir}/${identifier}_${progressbaridx}_zenityprogresspid")" || true
          ## Check if still running.
          local ps__p_exit_code
          ps__p_exit_code="0"
@@ -738,7 +722,7 @@ return_status() {
 
    ## {{ --progressbarxprogresstxtexisting
    if [ "$progressbarxprogresstxtexisting" = "1" ]; then
-      if [ -f "/run/msgcollector/$who_ami/${identifier}_${progressbaridx}_progresstxt" ]; then
+      if [ -f "${msgcollector_run_dir}/${identifier}_${progressbaridx}_progresstxt" ]; then
          exit 0
       else
          exit 1
@@ -748,7 +732,7 @@ return_status() {
 
    ## {{ --typexstatus
    if [ "$typex_chosen" = "1" ]; then
-      write_to_file="/run/msgcollector/$who_ami/${identifier}_typex"
+      write_to_file="${msgcollector_run_dir}/${identifier}_typex"
       if [ -f "$write_to_file" ]; then
          local TYPE
          TYPE="$(cat "$write_to_file")"
@@ -760,7 +744,7 @@ return_status() {
 
    ## {{ --typeclistatus
    if [ "$typecli_chosen" = "1" ]; then
-      write_to_file="/run/msgcollector/$who_ami/${identifier}_typecli"
+      write_to_file="${msgcollector_run_dir}/${identifier}_typecli"
       if [ -f "$write_to_file" ]; then
          local TYPE
          TYPE="$(cat "$write_to_file")"
@@ -791,36 +775,36 @@ forget() {
    ## Setting progress to 100, so any eventually still open progress bars get closed.
    ## Deactivated.
    ## Problematic if a new progress bar will be started quickly afterward.
-   #/usr/libexec/msgcollector/msgprogress --identifier "$identifier" --whoami "$who_ami" --progress "100" & disown
+   #/usr/libexec/msgcollector/msgprogress --identifier "$identifier" --progress "100" & disown
 
    local file_list=(
-      "/run/msgcollector/$who_ami/${identifier}_icon"
-      "/run/msgcollector/$who_ami/${identifier}_titlecli"
-      "/run/msgcollector/$who_ami/${identifier}_titlex"
-      "/run/msgcollector/$who_ami/${identifier}_passivepopupqueuextitle"
-      "/run/msgcollector/$who_ami/${identifier}_${progressbaridx}_progressbartitlex"
-      "/run/msgcollector/$who_ami/${identifier}_typecli"
-      "/run/msgcollector/$who_ami/${identifier}_typex"
-      "/run/msgcollector/$who_ami/${identifier}_progressbarx_done"
-      "/run/msgcollector/$who_ami/${identifier}_progressbarx"
-      "/run/msgcollector/$who_ami/${identifier}_passivepopupqueuex_done"
-      "/run/msgcollector/$who_ami/${identifier}_passivepopupqueuex"
-      "/run/msgcollector/$who_ami/${identifier}_messagex_done"
-      "/run/msgcollector/$who_ami/${identifier}_messagex"
-      "/run/msgcollector/$who_ami/${identifier}_waitmessagecli_done"
-      "/run/msgcollector/$who_ami/${identifier}_waitmessagecli"
-      "/run/msgcollector/$who_ami/${identifier}_messagecli_done"
-      "/run/msgcollector/$who_ami/${identifier}_messagecli"
-      "/run/msgcollector/$who_ami/${identifier}_forceactive"
-      "/run/msgcollector/$who_ami/${identifier}_lefttop"
-      "/run/msgcollector/$who_ami/${identifier}_parenttty"
+      "${msgcollector_run_dir}/${identifier}_icon"
+      "${msgcollector_run_dir}/${identifier}_titlecli"
+      "${msgcollector_run_dir}/${identifier}_titlex"
+      "${msgcollector_run_dir}/${identifier}_passivepopupqueuextitle"
+      "${msgcollector_run_dir}/${identifier}_${progressbaridx}_progressbartitlex"
+      "${msgcollector_run_dir}/${identifier}_typecli"
+      "${msgcollector_run_dir}/${identifier}_typex"
+      "${msgcollector_run_dir}/${identifier}_progressbarx_done"
+      "${msgcollector_run_dir}/${identifier}_progressbarx"
+      "${msgcollector_run_dir}/${identifier}_passivepopupqueuex_done"
+      "${msgcollector_run_dir}/${identifier}_passivepopupqueuex"
+      "${msgcollector_run_dir}/${identifier}_messagex_done"
+      "${msgcollector_run_dir}/${identifier}_messagex"
+      "${msgcollector_run_dir}/${identifier}_waitmessagecli_done"
+      "${msgcollector_run_dir}/${identifier}_waitmessagecli"
+      "${msgcollector_run_dir}/${identifier}_messagecli_done"
+      "${msgcollector_run_dir}/${identifier}_messagecli"
+      "${msgcollector_run_dir}/${identifier}_forceactive"
+      "${msgcollector_run_dir}/${identifier}_lefttop"
+      "${msgcollector_run_dir}/${identifier}_parenttty"
    )
 
    ## Better not deleting
-   ## "/run/msgcollector/$who_ami/${identifier}_${progressbaridx}_parentpid"
-   ## "/run/msgcollector/$who_ami/${identifier}_${progressbaridx}_fifo"
-   ## "/run/msgcollector/$who_ami/${identifier}_${progressbaridx}_progresstxt"
-   ## "/run/msgcollector/$who_ami/${identifier}_${progressbaridx}_zenityprogresspid"
+   ## "${msgcollector_run_dir}/${identifier}_${progressbaridx}_parentpid"
+   ## "${msgcollector_run_dir}/${identifier}_${progressbaridx}_fifo"
+   ## "${msgcollector_run_dir}/${identifier}_${progressbaridx}_progresstxt"
+   ## "${msgcollector_run_dir}/${identifier}_${progressbaridx}_zenityprogresspid"
    ## because that could confuse /usr/libexec/msgcollector/msgprogress.
 
    local file_name
@@ -836,8 +820,8 @@ forgetwaitcli() {
    trap "error_handler" ERR
 
    local file_list=(
-      "/run/msgcollector/$who_ami/${identifier}_waitmessagecli_done"
-      "/run/msgcollector/$who_ami/${identifier}_waitmessagecli"
+      "${msgcollector_run_dir}/${identifier}_waitmessagecli_done"
+      "${msgcollector_run_dir}/${identifier}_waitmessagecli"
    )
 
    local file_name
@@ -856,6 +840,10 @@ forgetwaitcli() {
 parse_cmd_options "$@"
 
 source /usr/libexec/msgcollector/msgcollector_shared
+## sets: ${msgcollector_run_dir}
+folder_init
+
+## provided by: /usr/libexec/msgcollector/msgcollector_shared
 maybe_wait
 
 if [ "$forget" = "1" ]; then
