fix

diff --git a/usr/libexec/msgcollector/msgprogressbar b/usr/libexec/msgcollector/msgprogressbar
--- a/usr/libexec/msgcollector/msgprogressbar
+++ b/usr/libexec/msgcollector/msgprogressbar
@@ -13,7 +13,7 @@ set -o errtrace
 
 source /usr/libexec/helper-scripts/light_sleep.bsh
 
-scriptname="$(basename "$BASH_SOURCE")"
+scriptname="$(basename -- "$BASH_SOURCE")"
 
 timeout_command=("timeout" "--kill-after" "1" "2")
 
@@ -36,7 +36,7 @@ error_handler() {
    if [ ! -d ~/".msgcollector" ]; then
       "${timeout_command[@]}" mkdir --parents -- ~/".msgcollector"
    fi
-   echo "$scriptname: BASH_COMMAND: $BASH_COMMAND | exit_code: $exit_code" | "${timeout_command[@]}" tee -a -- ~/".msgcollector/msgdispatcher-error.log" >/dev/null
+   echo "$0: BASH_COMMAND: $BASH_COMMAND | exit_code: $exit_code" | "${timeout_command[@]}" tee -a -- ~/".msgcollector/msgdispatcher-error.log" >/dev/null
    exit 1
 }
 
@@ -73,7 +73,7 @@ parse_cmd_options() {
                message="$2"
                shift 2
                if [ "$message" = "" ]; then
-                  echo "$BASH_SOURCE ERROR: variable message is empty."
+                  echo "$0: ERROR: variable message is empty."
                   exit 1
                fi
                ;;
@@ -82,7 +82,7 @@ parse_cmd_options() {
                break
                ;;
            -*)
-               echo "$scriptname unknown option: $1" >&2
+               echo "$0: unknown option: $1" >&2
                exit 1
                ;;
            *)
