printf

diff --git a/usr/libexec/msgcollector/msgprogressbar b/usr/libexec/msgcollector/msgprogressbar
--- a/usr/libexec/msgcollector/msgprogressbar
+++ b/usr/libexec/msgcollector/msgprogressbar
@@ -32,11 +32,11 @@ error_handler() {
 ## exit_code: $exit_code
 ###############################################################################\
 "
-   echo "$msg" >&2
+   printf '%s\n' "$msg" >&2
    if [ ! -d ~/".msgcollector" ]; then
       "${timeout_command[@]}" mkdir --parents -- ~/".msgcollector"
    fi
-   echo "$0: BASH_COMMAND: $BASH_COMMAND | exit_code: $exit_code" | "${timeout_command[@]}" tee -a -- ~/".msgcollector/msgdispatcher-error.log" >/dev/null
+   printf '%s\n' "$0: BASH_COMMAND: $BASH_COMMAND | exit_code: $exit_code" | "${timeout_command[@]}" tee -a -- ~/".msgcollector/msgdispatcher-error.log" >/dev/null
    exit 1
 }
 
@@ -73,7 +73,7 @@ parse_cmd_options() {
                message="$2"
                shift 2
                if [ "$message" = "" ]; then
-                  echo "$0: ERROR: variable message is empty."
+                  printf '%s\n' "$0: ERROR: variable message is empty."
                   exit 1
                fi
                ;;
@@ -82,7 +82,7 @@ parse_cmd_options() {
                break
                ;;
            -*)
-               echo "$0: unknown option: $1" >&2
+               printf '%s\n' "$0: unknown option: $1" >&2
                exit 1
                ;;
            *)
@@ -124,7 +124,7 @@ output_ex() {
    ## when $progress_txt_file contains 100.
 
    ## Debugging.
-   #echo "progress: $progress | caller: $PPID | $caller | killing $yad_progress_pid" >> /home/user/progresslog
+   #printf '%s\n' "progress: $progress | caller: $PPID | $caller | killing $yad_progress_pid" >> /home/user/progresslog
 
    if [ -f "$parent_pid_file" ]; then
       "${timeout_command[@]}" "/usr/libexec/msgcollector/msgprogressbar_kill_helper" "${identifier}" "${progressbaridx}"
@@ -237,7 +237,7 @@ start_progress_bar() {
 
    exec 3>"$fifo"
 
-   echo "$yad_progress_pid" > "$yad_progress_pid_file"
+   printf '%s\n' "$yad_progress_pid" > "$yad_progress_pid_file"
 
    while true "$0: main loop"; do
       true "$0: main loop started"
