improved init script

diff --git a/etc/init.d/msgcollector b/etc/init.d/msgcollector
--- a/etc/init.d/msgcollector
+++ b/etc/init.d/msgcollector
@@ -17,6 +17,15 @@
 
 # Do NOT "set -e"
 
+PATH=/sbin:/usr/sbin:/bin:/usr/bin
+DESC="msgcollector"
+NAME=msgcollector
+DAEMON=/usr/sbin/$NAME
+#DAEMON_ARGS="--options args"
+#PIDFILE=/var/run/$NAME.pid
+SCRIPTNAME=/etc/init.d/$NAME
+DONE_FILE="/var/run/msgcollector/init.done"
+
 #set -x
 
 # Exit if the package is not installed
@@ -30,17 +39,24 @@
 # and status_of_proc is working.
 . /lib/lsb/init-functions
 
-mkdir --mode o+rwx --parents /var/run/msgcollector
-setfacl --recursive --default --set u::rwx,g::rwx,o::rwx /var/run/msgcollector
-chmod --recursive g+rwx /var/run/msgcollector
-chmod --recursive o+rwx /var/run/msgcollector
-
 #
 # Function that starts the daemon/service
 #
 do_start()
 {
-   return 0
+	# Return
+	#   0 if daemon has been started
+	#   1 if daemon was already running
+	#   2 if daemon could not be started
+	mkdir --mode o+rwx --parents /var/run/msgcollector || return 2
+	setfacl --recursive --default --set u::rwx,g::rwx,o::rwx /var/run/msgcollector || return 2
+	chmod --recursive g+rwx /var/run/msgcollector || return 2
+	chmod --recursive o+rwx /var/run/msgcollector || return 2
+	touch "$DONE_FILE" || return 2
+	# Add code here, if necessary, that waits for the process to be ready
+	# to handle requests from services started subsequently which depend
+	# on this one.  As a last resort, sleep for some time.
+	return 0
 }
 
 #
@@ -48,29 +64,38 @@ do_start()
 #
 do_stop()
 {
-   return 0
+	# Return
+	#   0 if daemon has been stopped
+	#   1 if daemon was already stopped
+	#   2 if daemon could not be stopped
+	#   other if a failure occurred
+	return 0
 }
 
 do_status()
 {
-   return 0
+	if [ -f "$DONE_FILE" ]; then
+		return 0
+	else
+		return 1
+	fi
 }
 
 case "$1" in
   start)
-	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+	log_daemon_msg "Starting $DESC" "$NAME"
 	do_start
 	case "$?" in
-		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+		0|1) log_end_msg 0 ;;
+		2) log_end_msg 1 ;;
 	esac
 	;;
   stop)
-	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+	log_daemon_msg "Stopping $DESC" "$NAME"
 	do_stop
 	case "$?" in
-		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+		0|1) log_end_msg 0 ;;
+		2) log_end_msg 1 ;;
 	esac
 	;;
   status)
