fix

diff --git a/usr/lib/msgcollector/error_handler b/usr/lib/msgcollector/error_handler
--- a/usr/lib/msgcollector/error_handler
+++ b/usr/lib/msgcollector/error_handler
@@ -50,6 +50,25 @@ $error_text"
 <br></br>#########################################################################</p>"
    fi
 
+   ## Check if ex_funct command has been already defined. This is not the case,
+   ## when the script is terminated very early.
+   local command_v_output_exit_code
+   command_v_output_exit_code="0"
+   command -v "ex_funct" >/dev/null || { command_v_output_exit_code="$?" ; true; };
+   if [ "$command_v_output_exit_code" = "0" ]; then
+      echo "$SCRIPTNAME: Error detected. Cleaning up... Exiting..." >&2
+      SIGNAL_TYPE="ERR"
+      ex_funct || true
+      echo "$SCRIPTNAME: Error! ex_funct did not exit!" >&2
+      echo "$SCRIPTNAME: Exiting..." >&2
+      if [ "$EXIT_CODE" = "" ]; then
+         EXIT_CODE="1"
+      fi
+      exit "$EXIT_CODE"
+   else
+      echo "$SCRIPTNAME: Error detected. Skipping ex_funct since not yet load. Exiting..." >&2
+   fi
+
    ## Check if $output command has been already defined. This is not the case,
    ## when the script is terminated very early.
    local command_v_output_exit_code
@@ -67,19 +86,6 @@ $error_text"
       else
          echo "$stripped_msg" >&2
       fi
-   fi
-
-   ## Check if ex_funct command has been already defined. This is not the case,
-   ## when the script is terminated very early.
-   local command_v_output_exit_code
-   command_v_output_exit_code="0"
-   command -v "ex_funct" >/dev/null || { command_v_output_exit_code="$?" ; true; };
-   if [ "$command_v_output_exit_code" = "0" ]; then
-      echo "$SCRIPTNAME: Error detected. Cleaning up... Exiting..." >&2
-      SIGNAL_TYPE="ERR"
-      ex_funct || true
-   else
-      echo "$SCRIPTNAME: Error detected. Skipping ex_funct since not yet load. Exiting..." >&2
    fi
 
    if [ "$EXIT_CODE" = "" ]; then
