fix: made compatible for multi user environments

diff --git a/usr/lib/msgcollector/msgcollector b/usr/lib/msgcollector/msgcollector
--- a/usr/lib/msgcollector/msgcollector
+++ b/usr/lib/msgcollector/msgcollector
@@ -5,18 +5,18 @@
 ## See the file COPYING for copying conditions.
 
 ## Examples:
-## /usr/lib/msgcollector/msgcollector --identifier whonixcheck --icon /usr/share/icons/anon-icon-pack/whonix.ico --parentpid "$$" --typecli "warning" --titlecli "test title" --messagecli --message "test"
-## /usr/lib/msgcollector/msgcollector --identifier whonixcheck --icon /usr/share/icons/anon-icon-pack/whonix.ico --parentpid "$$" --typex "warning" --titlex "test title" --messagex --message "test" --lefttop
-## /usr/lib/msgcollector/msgcollector --identifier whonixcheck --icon /usr/share/icons/anon-icon-pack/whonix.ico --parentpid "$$" --typex "warning" --titlex "test title" --waitmessagex --message "test"
-## /usr/lib/msgcollector/msgcollector --identifier whonixcheck --icon /usr/share/icons/anon-icon-pack/whonix.ico --parentpid "$$" --typex "warning" --titlex "test title" --passivepopupqueuex --message "test"
-## /usr/lib/msgcollector/msgcollector --identifier whonixcheck --icon /usr/share/icons/anon-icon-pack/whonix.ico --parentpid "$$" --typex "warning" --titlex "test title" --progressbarx --message "test" --done
-## /usr/lib/msgcollector/msgcollector --identifier whonixcheck --icon /usr/share/icons/anon-icon-pack/whonix.ico --parentpid "$$" --progressx "50"
+## /usr/lib/msgcollector/msgcollector --identifier whonixcheck --whoami user --icon /usr/share/icons/anon-icon-pack/whonix.ico --parentpid "$$" --typecli "warning" --titlecli "test title" --messagecli --message "test"
+## /usr/lib/msgcollector/msgcollector --identifier whonixcheck --whoami user --icon /usr/share/icons/anon-icon-pack/whonix.ico --parentpid "$$" --typex "warning" --titlex "test title" --messagex --message "test" --lefttop
+## /usr/lib/msgcollector/msgcollector --identifier whonixcheck --whoami user --icon /usr/share/icons/anon-icon-pack/whonix.ico --parentpid "$$" --typex "warning" --titlex "test title" --waitmessagex --message "test"
+## /usr/lib/msgcollector/msgcollector --identifier whonixcheck --whoami user --icon /usr/share/icons/anon-icon-pack/whonix.ico --parentpid "$$" --typex "warning" --titlex "test title" --passivepopupqueuex --message "test"
+## /usr/lib/msgcollector/msgcollector --identifier whonixcheck --whoami user --icon /usr/share/icons/anon-icon-pack/whonix.ico --parentpid "$$" --typex "warning" --titlex "test title" --progressbarx --message "test" --done
+## /usr/lib/msgcollector/msgcollector --identifier whonixcheck --whoami user --icon /usr/share/icons/anon-icon-pack/whonix.ico --parentpid "$$" --progressx "50"
 ## /usr/lib/msgcollector/msgdispatcher --x
 ## /usr/lib/msgcollector/msgdispatcher --cli
 
 ## Tests:
-## /usr/lib/msgcollector/msgcollector --identifier whonixcheck --icon /usr/share/icons/anon-icon-pack/whonix.ico --parentpid "$$" --typex "warning" --titlex "test title" --progressbaridx "test" --progressbarx --message "test" --done
-## /usr/lib/msgcollector/msgcollector --icon /usr/share/icons/anon-icon-pack/timesync.ico --parentpid 8196 --identifier whonixcheck --progressbaridx "test" --progressx 100
+## /usr/lib/msgcollector/msgcollector --identifier whonixcheck --whoami user --icon /usr/share/icons/anon-icon-pack/whonix.ico --parentpid "$$" --typex "warning" --titlex "test title" --progressbaridx "test" --progressbarx --message "test" --done
+## /usr/lib/msgcollector/msgcollector --icon /usr/share/icons/anon-icon-pack/timesync.ico --parentpid 8196 --identifier whonixcheck --whoami user --progressbaridx "test" --progressx 100
 
 #set -x
 set -o pipefail
@@ -85,6 +85,10 @@ parse_cmd_options() {
                ;;
            --identifier)
                identifier="$2"
+               shift 2
+               ;;
+           --whoami)
+               whoami="$2"
                shift 2
                ;;
            --icon)
@@ -229,6 +233,14 @@ parse_cmd_options() {
    fi
 }
 
+preparation() {
+   trap "error_handler" ERR
+
+   if [ "$who_ami" = "" ]; then
+      who_ami="$(whoami)"
+   fi
+}
+
 colors() {
    trap "error_handler" ERR
 
@@ -358,7 +370,7 @@ collector() {
       echo "$0 ERROR: variable icon is empty."
       exit 1
    fi
-   echo "$icon" | sudo -u user tee "/var/run/msgcollector/${identifier}.icon" > /dev/null
+   echo "$icon" > "/var/run/msgcollector/$who_ami/${identifier}.icon"
    ## }}
 
    ## {{ --parentpid
@@ -370,90 +382,90 @@ collector() {
       parentpid="0000000000"
    fi
    ## Not at this point to avoid useless files.
-   #echo "$parentpid" | sudo -u user tee "/var/run/msgcollector/${identifier}.${progressbaridx}.parentpid" > /dev/null
+   #echo "$parentpid" > "/var/run/msgcollector/$who_ami/${identifier}.${progressbaridx}.parentpid"
    ## }}
 
    ## {{ --titlecli
    if [ ! -z "$titlecli" ]; then
       ## variable $titlecli exists
-      echo "$titlecli" | sudo -u user tee "/var/run/msgcollector/${identifier}.titlecli" > /dev/null
+      echo "$titlecli" > "/var/run/msgcollector/$who_ami/${identifier}.titlecli"
    fi
    ## }}
 
    ## {{ --titlex
    if [ ! -z "$titlex" ]; then
       ## variable $titlex exists
-      echo "$titlex" | sudo -u user tee "/var/run/msgcollector/${identifier}.titlex" > /dev/null
+      echo "$titlex" > "/var/run/msgcollector/$who_ami/${identifier}.titlex"
    fi
    ## }}
 
    ## {{ --typecli
-   if [ -f "/var/run/msgcollector/${identifier}.typecli" ]; then
-      old_typecli="$(cat "/var/run/msgcollector/${identifier}.typecli")"
+   if [ -f "/var/run/msgcollector/$who_ami/${identifier}.typecli" ]; then
+      old_typecli="$(cat "/var/run/msgcollector/$who_ami/${identifier}.typecli")"
    fi
 
    if [ "$old_typecli" = "info" ]; then
       if [ "$typecli" = "error" ]; then
          ## Upgrade from info to error.
-         echo "error" | sudo -u user tee "/var/run/msgcollector/${identifier}.typecli" > /dev/null
+         echo "error" > "/var/run/msgcollector/$who_ami/${identifier}.typecli"
       elif [ "$typecli" = "warning" ]; then
          ## Upgrade from info to warning.
-         echo "warning" | sudo -u user tee "/var/run/msgcollector/${identifier}.typecli" > /dev/null
+         echo "warning" > "/var/run/msgcollector/$who_ami/${identifier}.typecli"
       fi
    elif [ "$old_typecli" = "warning" ]; then
       if [ "$typecli" = "error" ]; then
          ## Upgrade from warning to error.
-         echo "error" | sudo -u user tee "/var/run/msgcollector/${identifier}.typecli" > /dev/null
+         echo "error" > "/var/run/msgcollector/$who_ami/${identifier}.typecli"
       fi
    elif [ "$old_typecli" = "error" ]; then
       true
    else
-      echo "$typecli" | sudo -u user tee "/var/run/msgcollector/${identifier}.typecli" > /dev/null
+      echo "$typecli" > "/var/run/msgcollector/$who_ami/${identifier}.typecli"
    fi
    ## }}
 
    ## {{ --typex
-   if [ -f "/var/run/msgcollector/${identifier}.typex" ]; then
-      old_typex="$(cat "/var/run/msgcollector/${identifier}.typex")"
+   if [ -f "/var/run/msgcollector/$who_ami/${identifier}.typex" ]; then
+      old_typex="$(cat "/var/run/msgcollector/$who_ami/${identifier}.typex")"
    fi
 
    if [ "$old_typex" = "info" ]; then
       if [ "$typex" = "error" ]; then
          ## Upgrade from info to error.
-         echo "error" | sudo -u user tee "/var/run/msgcollector/${identifier}.typex" > /dev/null
+         echo "error" > "/var/run/msgcollector/$who_ami/${identifier}.typex"
       elif [ "$typex" = "warning" ]; then
          ## Upgrade from info to warning.
-         echo "warning" | sudo -u user tee "/var/run/msgcollector/${identifier}.typex" > /dev/null
+         echo "warning" > "/var/run/msgcollector/$who_ami/${identifier}.typex"
       fi
    elif [ "$old_typex" = "warning" ]; then
       if [ "$typex" = "error" ]; then
          ## Upgrade from warning to error.
-         echo "error" | sudo -u user tee "/var/run/msgcollector/${identifier}.typex" > /dev/null
+         echo "error" > "/var/run/msgcollector/$who_ami/${identifier}.typex"
       fi
    elif [ "$old_typex" = "error" ]; then
       true
    else
-      echo "$typex" | sudo -u user tee "/var/run/msgcollector/${identifier}.typex" > /dev/null
+      echo "$typex" > "/var/run/msgcollector/$who_ami/${identifier}.typex"
    fi
    ## }}
 
    ## {{ --messagex
    if [ "$messagex" = "1" ]; then
-      write_to_file="/var/run/msgcollector/${identifier}.messagex"
+      write_to_file="/var/run/msgcollector/$who_ami/${identifier}.messagex"
       append_to_file
    fi
    ## }}
 
    ## {{ --waitmessagex
    if [ "$waitmessagex" = "1" ]; then
-      write_to_file="/var/run/msgcollector/${identifier}.waitmessagex"
+      write_to_file="/var/run/msgcollector/$who_ami/${identifier}.waitmessagex"
       append_to_file
    fi
    ## }}
 
    ## {{ --messagecli
    if [ "$messagecli" = "1" ]; then
-      write_to_file="/var/run/msgcollector/${identifier}.messagecli"
+      write_to_file="/var/run/msgcollector/$who_ami/${identifier}.messagecli"
       if [ ! -z "$message" ]; then
          ## variable $message exists
          pretty_type "$typecli"
@@ -466,7 +478,7 @@ collector() {
 
    ## {{ --waitmessagecli
    if [ "$waitmessagecli" = "1" ]; then
-      write_to_file="/var/run/msgcollector/${identifier}.waitmessagecli"
+      write_to_file="/var/run/msgcollector/$who_ami/${identifier}.waitmessagecli"
       if [ ! -z "$message" ]; then
          ## variable $message exists
          pretty_type "$typecli"
@@ -479,14 +491,14 @@ collector() {
 
    ## {{ --passivepopupqueuex
    if [ "$passivepopupqueuex" = "1" ]; then
-      write_to_file="/var/run/msgcollector/${identifier}.passivepopupqueuex"
+      write_to_file="/var/run/msgcollector/$who_ami/${identifier}.passivepopupqueuex"
       append_to_file
    fi
    ## }}
 
    ## {{ --animate
    if [ "$animate" = "1" ]; then
-      touch "/var/run/msgcollector/${identifier}.${progressbaridx}.progressbarx.animate"
+      touch "/var/run/msgcollector/$who_ami/${identifier}.${progressbaridx}.progressbarx.animate"
    fi
 
    ## {{ --progressx
@@ -501,7 +513,7 @@ collector() {
       #echo "msgcollector: progressx: $progressx | caller: $PPID | $caller" >> /home/user/progresslog
 
       ## & disown to prevent long waiting.
-      /usr/lib/msgcollector/msgprogress --identifier "$identifier" --progressbaridx "${progressbaridx}" --progress "$progressx" & disown
+      /usr/lib/msgcollector/msgprogress --identifier "$identifier" --whoami "$who_ami" --progressbaridx "${progressbaridx}" --progress "$progressx" & disown
    fi
    ## }}
 
@@ -511,27 +523,27 @@ collector() {
          error "Variable progressbaridx is empty."
          exit 4
       fi
-      echo "$parentpid" | sudo -u user tee "/var/run/msgcollector/${identifier}.${progressbaridx}.parentpid" > /dev/null
-      write_to_file="/var/run/msgcollector/${identifier}.${progressbaridx}.progressbarx"
+      echo "$parentpid" > "/var/run/msgcollector/$who_ami/${identifier}.${progressbaridx}.parentpid"
+      write_to_file="/var/run/msgcollector/$who_ami/${identifier}.${progressbaridx}.progressbarx"
       append_to_file
    fi
    ## }}
 
    ## {{ --forceactive
    if [ "$forceactive" = "1" ]; then
-      sudo -u user touch "/var/run/msgcollector/${identifier}.forceactive"
+      sudo -u user touch "/var/run/msgcollector/$who_ami/${identifier}.forceactive"
    fi
    ## }}
 
    ## {{ --lefttop
    if [ "$lefttop" = "1" ]; then
-      sudo -u user touch "/var/run/msgcollector/${identifier}.lefttop"
+      sudo -u user touch "/var/run/msgcollector/$who_ami/${identifier}.lefttop"
    fi
    ## }}
 
    ## {{ --parenttty
    if [ ! -z "$parenttty" ]; then
-      echo "$parenttty" > "/var/run/msgcollector/${identifier}.parenttty"
+      echo "$parenttty" > "/var/run/msgcollector/$who_ami/${identifier}.parenttty"
    fi
    ## }}
 }
@@ -543,16 +555,16 @@ append_to_file() {
       ## variable $message exists
       if [ "$newlinecli" = "1" ]; then
          echo "
-$message" | sudo -u user tee --append "$write_to_file" > /dev/null
+$message" >> "$write_to_file"
       elif [ "$messagex" = 1 ]; then
          if [ "$nonewlinex" = "1" ]; then
-            echo "$message" | sudo -u user tee --append "$write_to_file" > /dev/null
+            echo "$message" >> "$write_to_file"
          else
             echo "$message
-" | sudo -u user tee --append "$write_to_file" > /dev/null
+" >> "$write_to_file"
          fi
       else
-         echo "$message" | sudo -u user tee --append "$write_to_file" > /dev/null
+         echo "$message" >> "$write_to_file"
       fi
    fi
 
@@ -575,35 +587,35 @@ return_status() {
 
    ## {{ --messagex
    if [ "$messagex" = "1" ]; then
-      write_to_file="/var/run/msgcollector/${identifier}.messagex"
+      write_to_file="/var/run/msgcollector/$who_ami/${identifier}.messagex"
       return_status_file
    fi
    ## }}
 
    ## {{ --waitmessagex
    if [ "$waitmessagex" = "1" ]; then
-      write_to_file="/var/run/msgcollector/${identifier}.waitmessagex"
+      write_to_file="/var/run/msgcollector/$who_ami/${identifier}.waitmessagex"
       return_status_file
    fi
    ## }}
 
    ## {{ --messagecli
    if [ "$messagecli" = "1" ]; then
-      write_to_file="/var/run/msgcollector/${identifier}.messagecli"
+      write_to_file="/var/run/msgcollector/$who_ami/${identifier}.messagecli"
       return_status_file
    fi
    ## }}
 
    ## {{ --waitmessagecli
    if [ "$waitmessagecli" = "1" ]; then
-      write_to_file="/var/run/msgcollector/${identifier}.waitmessagecli"
+      write_to_file="/var/run/msgcollector/$who_ami/${identifier}.waitmessagecli"
       return_status_file
    fi
    ## }}
 
    ## {{ --passivepopupqueuex
    if [ "$passivepopupqueuex" = "1" ]; then
-      write_to_file="/var/run/msgcollector/${identifier}.passivepopupqueuex"
+      write_to_file="/var/run/msgcollector/$who_ami/${identifier}.passivepopupqueuex"
       return_status_file
    fi
    ## }}
@@ -614,7 +626,7 @@ return_status() {
          error "Variable progressbaridx is empty."
          exit 4
       fi
-      write_to_file="/var/run/msgcollector/${identifier}.${progressbaridx}.progressbarx"
+      write_to_file="/var/run/msgcollector/$who_ami/${identifier}.${progressbaridx}.progressbarx"
       return_status_file
    fi
    ## }}
@@ -640,36 +652,36 @@ forget() {
    ## Setting progress to 100, so any eventually still open progress bars get closed.
    ## Deactivated.
    ## Problematic if a new progress bar will be started quickly afterward.
-   #/usr/lib/msgcollector/msgprogress --identifier "$identifier" --progress "100" & disown
+   #/usr/lib/msgcollector/msgprogress --identifier "$identifier" --whoami "$who_ami" --progress "100" & disown
 
    local file_list=(
-      "/var/run/msgcollector/${identifier}.icon"
-      "/var/run/msgcollector/${identifier}.titlecli"
-      "/var/run/msgcollector/${identifier}.titlex"
-      "/var/run/msgcollector/${identifier}.typecli"
-      "/var/run/msgcollector/${identifier}.typex"
-      "/var/run/msgcollector/${identifier}.progressbarx.done"
-      "/var/run/msgcollector/${identifier}.progressbarx"
-      "/var/run/msgcollector/${identifier}.passivepopupqueuex.done"
-      "/var/run/msgcollector/${identifier}.passivepopupqueuex"
-      "/var/run/msgcollector/${identifier}.waitmessagex.done"
-      "/var/run/msgcollector/${identifier}.waitmessagex"
-      "/var/run/msgcollector/${identifier}.messagex.done"
-      "/var/run/msgcollector/${identifier}.messagex"
-      "/var/run/msgcollector/${identifier}.waitmessagecli.done"
-      "/var/run/msgcollector/${identifier}.waitmessagecli"
-      "/var/run/msgcollector/${identifier}.messagecli.done"
-      "/var/run/msgcollector/${identifier}.messagecli"
-      "/var/run/msgcollector/${identifier}.forceactive"
-      "/var/run/msgcollector/${identifier}.lefttop"
-      "/var/run/msgcollector/${identifier}.parenttty"
+      "/var/run/msgcollector/$who_ami/${identifier}.icon"
+      "/var/run/msgcollector/$who_ami/${identifier}.titlecli"
+      "/var/run/msgcollector/$who_ami/${identifier}.titlex"
+      "/var/run/msgcollector/$who_ami/${identifier}.typecli"
+      "/var/run/msgcollector/$who_ami/${identifier}.typex"
+      "/var/run/msgcollector/$who_ami/${identifier}.progressbarx.done"
+      "/var/run/msgcollector/$who_ami/${identifier}.progressbarx"
+      "/var/run/msgcollector/$who_ami/${identifier}.passivepopupqueuex.done"
+      "/var/run/msgcollector/$who_ami/${identifier}.passivepopupqueuex"
+      "/var/run/msgcollector/$who_ami/${identifier}.waitmessagex.done"
+      "/var/run/msgcollector/$who_ami/${identifier}.waitmessagex"
+      "/var/run/msgcollector/$who_ami/${identifier}.messagex.done"
+      "/var/run/msgcollector/$who_ami/${identifier}.messagex"
+      "/var/run/msgcollector/$who_ami/${identifier}.waitmessagecli.done"
+      "/var/run/msgcollector/$who_ami/${identifier}.waitmessagecli"
+      "/var/run/msgcollector/$who_ami/${identifier}.messagecli.done"
+      "/var/run/msgcollector/$who_ami/${identifier}.messagecli"
+      "/var/run/msgcollector/$who_ami/${identifier}.forceactive"
+      "/var/run/msgcollector/$who_ami/${identifier}.lefttop"
+      "/var/run/msgcollector/$who_ami/${identifier}.parenttty"
    )
 
    ## Better not deleting
-   ## "/var/run/msgcollector/${identifier}.${progressbaridx}.parentpid"
-   ## "/var/run/msgcollector/${identifier}.${progressbaridx}.fifo"
-   ## "/var/run/msgcollector/${identifier}.${progressbaridx}.progresstxt"
-   ## "/var/run/msgcollector/${identifier}.${progressbaridx}.zenityprogresspid"
+   ## "/var/run/msgcollector/$who_ami/${identifier}.${progressbaridx}.parentpid"
+   ## "/var/run/msgcollector/$who_ami/${identifier}.${progressbaridx}.fifo"
+   ## "/var/run/msgcollector/$who_ami/${identifier}.${progressbaridx}.progresstxt"
+   ## "/var/run/msgcollector/$who_ami/${identifier}.${progressbaridx}.zenityprogresspid"
    ## because that could confuse /usr/lib/msgcollector/msgprogress.
 
    local file_name
@@ -685,8 +697,8 @@ forgetwaitcli() {
    trap "error_handler" ERR
 
    local file_list=(
-      "/var/run/msgcollector/${identifier}.waitmessagecli.done"
-      "/var/run/msgcollector/${identifier}.waitmessagecli"
+      "/var/run/msgcollector/$who_ami/${identifier}.waitmessagecli.done"
+      "/var/run/msgcollector/$who_ami/${identifier}.waitmessagecli"
    )
 
    local file_name
@@ -703,6 +715,7 @@ forgetwaitcli() {
 #" >> "/home/user/msgcollector"
 
 parse_cmd_options ${1+"$@"}
+preparation
 
 if [ "$forget" = "1" ]; then
    forget
diff --git a/usr/lib/msgcollector/msgdispatcher b/usr/lib/msgcollector/msgdispatcher
--- a/usr/lib/msgcollector/msgdispatcher
+++ b/usr/lib/msgcollector/msgdispatcher
@@ -81,13 +81,19 @@ parse_cmd_options() {
    done
 }
 
+preparation() {
+   trap "error_handler" ERR
+
+   who_ami="$(whoami)"
+}
+
 write_own_pid() {
    if [ "$cli" = "1" ]; then
-      echo "$$" > "/var/run/msgcollector/msgdispatcher_pidcli"
+      echo "$$" > "/var/run/msgcollector/$who_ami/msgdispatcher_pidcli"
    elif [ "$x" = "1" ]; then
-      echo "$$" > "/var/run/msgcollector/msgdispatcher_pidx"
+      echo "$$" > "/var/run/msgcollector/$who_ami/msgdispatcher_pidx"
    else
-      echo "$$" > "/var/run/msgcollector/msgdispatcher_piderror"
+      echo "$$" > "/var/run/msgcollector/$who_ami/msgdispatcher_piderror"
       exit 3
    fi
 }
@@ -97,7 +103,7 @@ output_write_to_tty() {
    trap "error_handler" ERR
 
    local lockfile
-   lockfile="/var/run/msgcollector/write_lock"
+   lockfile="/var/run/msgcollector/$who_ami/write_lock"
 
    (
       trap "error_handler" ERR
@@ -143,9 +149,9 @@ passive_popup_tool() {
 dispatch_cli() {
    trap "error_handler" ERR
 
-   if [ -f "/var/run/msgcollector/${identifier}.parenttty" ]; then
+   if [ -f "/var/run/msgcollector/$who_ami/${identifier}.parenttty" ]; then
       local parenttty
-      parenttty="$(cat "/var/run/msgcollector/${identifier}.parenttty")"
+      parenttty="$(cat "/var/run/msgcollector/$who_ami/${identifier}.parenttty")"
       if [ "$parenttty" = "/dev/tty1" ]; then
          ## When for example whonixcheck was run in tty1, then messages were
          ## already echoed by msgcollector. No need to dispatch them again.
@@ -160,14 +166,14 @@ dispatch_cli() {
 dispatch_x_active() {
    trap "error_handler" ERR
 
-   if [ -f "/var/run/msgcollector/${identifier}.lefttop" ]; then
+   if [ -f "/var/run/msgcollector/$who_ami/${identifier}.lefttop" ]; then
       local lefttop
       lefttop="1"
    fi
 
-   if [ -f "/var/run/msgcollector/${identifier}.icon" ]; then
+   if [ -f "/var/run/msgcollector/$who_ami/${identifier}.icon" ]; then
       local icon
-      icon="$(cat "/var/run/msgcollector/${identifier}.icon")"
+      icon="$(cat "/var/run/msgcollector/$who_ami/${identifier}.icon")"
    else
       ## Fallback.
       local icon
@@ -226,11 +232,11 @@ main_function() {
 
    while true; do
       unset identifier_list identifier temp_list temp_item
-      temp_list="/var/run/msgcollector/"*".done"
+      temp_list="/var/run/msgcollector/$who_ami/"*".done"
       for temp_item in $temp_list; do
          ## Remove ".done".
          temp_item="${temp_item%%.*}"
-         ## Remove "/var/run/msgcollector/".
+         ## Remove "/var/run/msgcollector/$who_ami/".
          temp_item="${temp_item##*/}"
          if [ "$identifier_list" = "" ]; then
             identifier_list="$temp_item"
@@ -243,97 +249,97 @@ main_function() {
 
             local progressbaridx_file
             ## The * matches progressbaridx.
-            for progressbaridx_file in /var/run/msgcollector/${identifier}.*.progressbarx.done; do
+            for progressbaridx_file in /var/run/msgcollector/$who_ami/${identifier}.*.progressbarx.done; do
                first_two="${progressbaridx_file%.*.*}"
                progressbaridx=${first_two##*.}
-               if [ -f "/var/run/msgcollector/${identifier}.${progressbaridx}.progressbarx.done" ]; then
-                  if [ -f "/var/run/msgcollector/${identifier}.${progressbaridx}.progressbarx" ]; then
-                     if [ -f "/var/run/msgcollector/${identifier}.${progressbaridx}.progressbarx.animate" ]; then
-                        rm --force "/var/run/msgcollector/${identifier}.${progressbaridx}.progressbarx.animate"
+               if [ -f "/var/run/msgcollector/$who_ami/${identifier}.${progressbaridx}.progressbarx.done" ]; then
+                  if [ -f "/var/run/msgcollector/$who_ami/${identifier}.${progressbaridx}.progressbarx" ]; then
+                     if [ -f "/var/run/msgcollector/$who_ami/${identifier}.${progressbaridx}.progressbarx.animate" ]; then
+                        rm --force "/var/run/msgcollector/$who_ami/${identifier}.${progressbaridx}.progressbarx.animate"
                         animate="--animate"
                      else
                         unset animate
                      fi
                      if [ "$verbose" = "1" ]; then
-                        bash -x /usr/lib/msgcollector/msgprogressbar --identifier "$identifier" --progressbaridx "${progressbaridx}" --verbose $animate
+                        bash -x /usr/lib/msgcollector/msgprogressbar --identifier "$identifier" --whoami "$who_ami" --progressbaridx "${progressbaridx}" --verbose $animate
                      else
-                        /usr/lib/msgcollector/msgprogressbar --identifier "$identifier" --progressbaridx "${progressbaridx}" $animate &
+                        /usr/lib/msgcollector/msgprogressbar --identifier "$identifier" --whoami "$who_ami" --progressbaridx "${progressbaridx}" $animate &
                      fi
                      unset animate
-                     rm --force "/var/run/msgcollector/${identifier}.${progressbaridx}.progressbarx.done"
+                     rm --force "/var/run/msgcollector/$who_ami/${identifier}.${progressbaridx}.progressbarx.done"
                   else
-                     rm --force "/var/run/msgcollector/${identifier}.${progressbaridx}.progressbarx.done"
+                     rm --force "/var/run/msgcollector/$who_ami/${identifier}.${progressbaridx}.progressbarx.done"
                   fi
                fi
             done
             unset progressbaridx_file
 
-            if [ -f "/var/run/msgcollector/${identifier}.waitmessagex.done" ]; then
-               if [ -f "/var/run/msgcollector/${identifier}.waitmessagex" ]; then
-                  msg="$(cat "/var/run/msgcollector/${identifier}.waitmessagex")"
-                  title="$(cat "/var/run/msgcollector/${identifier}.titlex")"
-                  type="$(cat "/var/run/msgcollector/${identifier}.typex")"
+            if [ -f "/var/run/msgcollector/$who_ami/${identifier}.waitmessagex.done" ]; then
+               if [ -f "/var/run/msgcollector/$who_ami/${identifier}.waitmessagex" ]; then
+                  msg="$(cat "/var/run/msgcollector/$who_ami/${identifier}.waitmessagex")"
+                  title="$(cat "/var/run/msgcollector/$who_ami/${identifier}.titlex")"
+                  type="$(cat "/var/run/msgcollector/$who_ami/${identifier}.typex")"
                   dispatch_x_passive "$type" "$msg"
-                  rm --force "/var/run/msgcollector/${identifier}.waitmessagex.done"
-                  rm --force "/var/run/msgcollector/${identifier}.waitmessagex"
+                  rm --force "/var/run/msgcollector/$who_ami/${identifier}.waitmessagex.done"
+                  rm --force "/var/run/msgcollector/$who_ami/${identifier}.waitmessagex"
                else
-                  rm --force "/var/run/msgcollector/${identifier}.waitmessagex.done"
+                  rm --force "/var/run/msgcollector/$who_ami/${identifier}.waitmessagex.done"
                fi
             fi
-            if [ -f "/var/run/msgcollector/${identifier}.messagex.done" ]; then
-               if [ -f "/var/run/msgcollector/${identifier}.messagex" ]; then
-                  msg="$(cat "/var/run/msgcollector/${identifier}.messagex")"
-                  title="$(cat "/var/run/msgcollector/${identifier}.titlex")"
-                  type="$(cat "/var/run/msgcollector/${identifier}.typex")"
+            if [ -f "/var/run/msgcollector/$who_ami/${identifier}.messagex.done" ]; then
+               if [ -f "/var/run/msgcollector/$who_ami/${identifier}.messagex" ]; then
+                  msg="$(cat "/var/run/msgcollector/$who_ami/${identifier}.messagex")"
+                  title="$(cat "/var/run/msgcollector/$who_ami/${identifier}.titlex")"
+                  type="$(cat "/var/run/msgcollector/$who_ami/${identifier}.typex")"
                   dispatch_x_active "$type" "$msg"
-                  rm --force "/var/run/msgcollector/${identifier}.messagex.done"
-                  rm --force "/var/run/msgcollector/${identifier}.messagex"
-                  rm --force "/var/run/msgcollector/${identifier}.lefttop"
+                  rm --force "/var/run/msgcollector/$who_ami/${identifier}.messagex.done"
+                  rm --force "/var/run/msgcollector/$who_ami/${identifier}.messagex"
+                  rm --force "/var/run/msgcollector/$who_ami/${identifier}.lefttop"
                else
                   ## Not using rm outside the if, to prevent race conditions.
                   ## Not always using rm, without if to prevent forking.
-                  rm --force "/var/run/msgcollector/${identifier}.messagex.done"
+                  rm --force "/var/run/msgcollector/$who_ami/${identifier}.messagex.done"
                fi
             fi
-            if [ -f "/var/run/msgcollector/${identifier}.passivepopupqueuex.done" ]; then
-               if [ -f "/var/run/msgcollector/${identifier}.passivepopupqueuex" ]; then
-                  msg="$(cat "/var/run/msgcollector/${identifier}.passivepopupqueuex")"
-                  title="$(cat "/var/run/msgcollector/${identifier}.titlex")"
-                  type="$(cat "/var/run/msgcollector/${identifier}.typex")"
-                  if [ -f "/var/run/msgcollector/${identifier}.forceactive" ]; then
+            if [ -f "/var/run/msgcollector/$who_ami/${identifier}.passivepopupqueuex.done" ]; then
+               if [ -f "/var/run/msgcollector/$who_ami/${identifier}.passivepopupqueuex" ]; then
+                  msg="$(cat "/var/run/msgcollector/$who_ami/${identifier}.passivepopupqueuex")"
+                  title="$(cat "/var/run/msgcollector/$who_ami/${identifier}.titlex")"
+                  type="$(cat "/var/run/msgcollector/$who_ami/${identifier}.typex")"
+                  if [ -f "/var/run/msgcollector/$who_ami/${identifier}.forceactive" ]; then
                      dispatch_x_active "$type" "$msg"
                   else
                      dispatch_x_passive "$type" "$msg"
                   fi
-                  rm --force "/var/run/msgcollector/${identifier}.forceactive"
-                  rm --force "/var/run/msgcollector/${identifier}.passivepopupqueuex.done"
-                  rm --force "/var/run/msgcollector/${identifier}.passivepopupqueuex"
+                  rm --force "/var/run/msgcollector/$who_ami/${identifier}.forceactive"
+                  rm --force "/var/run/msgcollector/$who_ami/${identifier}.passivepopupqueuex.done"
+                  rm --force "/var/run/msgcollector/$who_ami/${identifier}.passivepopupqueuex"
                else
-                  rm --force "/var/run/msgcollector/${identifier}.passivepopupqueuex.done"
+                  rm --force "/var/run/msgcollector/$who_ami/${identifier}.passivepopupqueuex.done"
                fi
             fi
 
          elif [ "$cli" = "1" ]; then
-            if [ -f "/var/run/msgcollector/${identifier}.waitmessagecli.done" ]; then
-               if [ -f "/var/run/msgcollector/${identifier}.waitmessagecli" ]; then
-                  msg="$(cat "/var/run/msgcollector/${identifier}.waitmessagecli")"
-                  type="$(cat "/var/run/msgcollector/${identifier}.typecli")"
+            if [ -f "/var/run/msgcollector/$who_ami/${identifier}.waitmessagecli.done" ]; then
+               if [ -f "/var/run/msgcollector/$who_ami/${identifier}.waitmessagecli" ]; then
+                  msg="$(cat "/var/run/msgcollector/$who_ami/${identifier}.waitmessagecli")"
+                  type="$(cat "/var/run/msgcollector/$who_ami/${identifier}.typecli")"
                   dispatch_cli "$msg"
-                  rm --force "/var/run/msgcollector/${identifier}.waitmessagecli.done"
-                  rm --force "/var/run/msgcollector/${identifier}.waitmessagecli"
+                  rm --force "/var/run/msgcollector/$who_ami/${identifier}.waitmessagecli.done"
+                  rm --force "/var/run/msgcollector/$who_ami/${identifier}.waitmessagecli"
                else
-                  rm --force "/var/run/msgcollector/${identifier}.waitmessagecli.done"
+                  rm --force "/var/run/msgcollector/$who_ami/${identifier}.waitmessagecli.done"
                fi
             fi
-            if [ -f "/var/run/msgcollector/${identifier}.messagecli.done" ]; then
-               if [ -f "/var/run/msgcollector/${identifier}.messagecli" ]; then
-                  msg="$(cat "/var/run/msgcollector/${identifier}.messagecli")"
-                  type="$(cat "/var/run/msgcollector/${identifier}.typecli")"
+            if [ -f "/var/run/msgcollector/$who_ami/${identifier}.messagecli.done" ]; then
+               if [ -f "/var/run/msgcollector/$who_ami/${identifier}.messagecli" ]; then
+                  msg="$(cat "/var/run/msgcollector/$who_ami/${identifier}.messagecli")"
+                  type="$(cat "/var/run/msgcollector/$who_ami/${identifier}.typecli")"
                   dispatch_cli "$msg"
-                  rm --force "/var/run/msgcollector/${identifier}.messagecli.done"
-                  rm --force "/var/run/msgcollector/${identifier}.messagecli"
+                  rm --force "/var/run/msgcollector/$who_ami/${identifier}.messagecli.done"
+                  rm --force "/var/run/msgcollector/$who_ami/${identifier}.messagecli"
                else
-                  rm --force "/var/run/msgcollector/${identifier}.messagecli.done"
+                  rm --force "/var/run/msgcollector/$who_ami/${identifier}.messagecli.done"
                fi
             fi
          else
@@ -346,6 +352,7 @@ main_function() {
 }
 
 parse_cmd_options ${1+"$@"}
+preparation
 write_own_pid
 source /usr/lib/msgcollector/msgwmctrl
 fallbacks ## provided by /usr/lib/msgcollector/msgwmctrl
