permission hardening
https://forums.whonix.org/t/msgcollector-security-hardening/7625

diff --git a/usr/lib/msgcollector/msgcollector b/usr/lib/msgcollector/msgcollector
--- a/usr/lib/msgcollector/msgcollector
+++ b/usr/lib/msgcollector/msgcollector
@@ -5,7 +5,7 @@
 
 #set -x
 set -o pipefail
-
+   echo "$0: \$@: $@"
 scriptname="$(basename "$BASH_SOURCE")"
 
 error_handler() {
@@ -14,7 +14,10 @@ error_handler() {
    local my_pstree
    my_pstree="$(pstree -p $$)" || true
    local ps_p_parentpid
-   ps_p_parentpid="$(ps -p "$parentpid")" || true
+
+   if [ ! "$parentpid" = "" ]; then
+      ps_p_parentpid="$(ps -p "$parentpid")" || true
+   fi
 
    local msg="\
 ###############################################################################
@@ -59,6 +62,8 @@ parse_cmd_options() {
    ## Thanks to:
    ## http://mywiki.wooledge.org/BashFAQ/035
 
+   who_ami=$(whoami)
+
    while true; do
        case $1 in
            --verbose)
@@ -75,7 +80,7 @@ parse_cmd_options() {
                shift 2
                ;;
            --whoami)
-               who_ami="$2"
+               who_ami_discard="$2"
                shift 2
                ;;
            --icon)
@@ -253,13 +258,20 @@ parse_cmd_options() {
 preparation() {
    trap "error_handler" ERR
 
+   ## TODO: msgdispatcher cannot read the file.
+   ## cat: /var/run/msgcollector/whonixcheck/whonixcheck.messagex: Permission denied
+   ## user running msgdispatcher (user "user") would need to be member of a group
+   ## which may read access all of folder /var/run/msgcollector.
+   #umask 006
+
    if [ "$who_ami" = "" ]; then
-      who_ami="$(whoami)"
+      echo "$0: ERROR: who_ami not set!"
+      exit 1
    fi
 
-   if [ ! -d "/var/run/msgcollector/$who_ami" ]; then
-      mkdir --mode o+rwx --parents "/var/run/msgcollector/$who_ami"
-   fi
+#    if [ ! -d "/var/run/msgcollector/$who_ami" ]; then
+#       mkdir --mode o+rwx --parents "/var/run/msgcollector/$who_ami"
+#    fi
 }
 
 colors() {
@@ -368,6 +380,12 @@ write_typecli_to_file() {
 
 collector() {
    trap "error_handler" ERR
+
+   if [ ! -d "/var/run/msgcollector/$who_ami" ]; then
+      mkdir -p "/var/run/msgcollector/$who_ami"
+   fi
+
+   echo "$0: who_ami: $who_ami"
 
    ## {{ --identifier
    if [ "${identifier}" = "" ]; then
@@ -603,7 +621,7 @@ $message" >> "$write_to_file"
 
    ## {{ --done
    if [ "$done" = "1" ]; then
-      touch "${write_to_file}.done"
+      touch "${write_to_file}_done"
    fi
    ## }}
 }
@@ -743,15 +761,15 @@ forget() {
       "/var/run/msgcollector/$who_ami/${identifier}.${progressbaridx}.progressbartitlex"
       "/var/run/msgcollector/$who_ami/${identifier}.typecli"
       "/var/run/msgcollector/$who_ami/${identifier}.typex"
-      "/var/run/msgcollector/$who_ami/${identifier}.progressbarx.done"
+      "/var/run/msgcollector/$who_ami/${identifier}.progressbarx_done"
       "/var/run/msgcollector/$who_ami/${identifier}.progressbarx"
-      "/var/run/msgcollector/$who_ami/${identifier}.passivepopupqueuex.done"
+      "/var/run/msgcollector/$who_ami/${identifier}.passivepopupqueuex_done"
       "/var/run/msgcollector/$who_ami/${identifier}.passivepopupqueuex"
-      "/var/run/msgcollector/$who_ami/${identifier}.messagex.done"
+      "/var/run/msgcollector/$who_ami/${identifier}.messagex_done"
       "/var/run/msgcollector/$who_ami/${identifier}.messagex"
-      "/var/run/msgcollector/$who_ami/${identifier}.waitmessagecli.done"
+      "/var/run/msgcollector/$who_ami/${identifier}.waitmessagecli_done"
       "/var/run/msgcollector/$who_ami/${identifier}.waitmessagecli"
-      "/var/run/msgcollector/$who_ami/${identifier}.messagecli.done"
+      "/var/run/msgcollector/$who_ami/${identifier}.messagecli_done"
       "/var/run/msgcollector/$who_ami/${identifier}.messagecli"
       "/var/run/msgcollector/$who_ami/${identifier}.forceactive"
       "/var/run/msgcollector/$who_ami/${identifier}.lefttop"
@@ -778,7 +796,7 @@ forgetwaitcli() {
    trap "error_handler" ERR
 
    local file_list=(
-      "/var/run/msgcollector/$who_ami/${identifier}.waitmessagecli.done"
+      "/var/run/msgcollector/$who_ami/${identifier}.waitmessagecli_done"
       "/var/run/msgcollector/$who_ami/${identifier}.waitmessagecli"
    )
 
