permission fixes

diff --git a/usr/lib/msgcollector/msgprogressbar b/usr/lib/msgcollector/msgprogressbar
--- a/usr/lib/msgcollector/msgprogressbar
+++ b/usr/lib/msgcollector/msgprogressbar
@@ -65,13 +65,17 @@ parse_cmd_options() {
                progressbartitlex="$2"
                shift 2
                ;;
-           --progressbarx)
-               progressbarx="$2"
-               shift 2
-               ;;
            --animate)
                animate="1"
                shift
+               ;;
+           --message)
+               message="$2"
+               shift 2
+               if [ "$message" = "" ]; then
+                  echo "$BASH_SOURCE ERROR: variable message is empty."
+                  exit 1
+               fi
                ;;
            --)
                shift
@@ -158,8 +162,8 @@ trap "output_sigterm" SIGTERM
 start_progress_bar() {
    trap "error_handler" ERR
 
-   if [ "$progressbarx" = "" ]; then
-      progressbarx="Progress bar message is empty, please report this Whonix bug!"
+   if [ "$message" = "" ]; then
+      message="Progress bar message is empty, please report this Whonix bug!"
    fi
 
    if [ "$progressbartitlex" = "" ]; then
@@ -236,7 +240,7 @@ start_progress_bar() {
       --auto-close \
       --progress \
       $percentage_maybe_add \
-      --text "$progressbarx" \
+      --text "$message" \
       < "$fifo" & zenity_progress_pid="$!"
 
    exec 3>"$fifo"
